const ADD_PLAYER = 'ADD_PLAYER';
const CHANGE_PLAYER = 'CHANGE_PLAYER';
const INCREMENT_THROWS = 'INCREMENT_THROWS';
const START_GAME = 'START_GAME';
const CLEAR_THROWS = 'CLEAR_THROWS';
const CHANGE_SCORE = 'CHANGE_SCORE';
const SET_WINNER = 'SET_WINNER';

export { 
    ADD_PLAYER, 
    CHANGE_PLAYER, 
    INCREMENT_THROWS, 
    START_GAME,
    CLEAR_THROWS,
    CHANGE_SCORE,
    SET_WINNER
};